name: 'PR Scan and Warn'
description: 'Scan the Changes in a PR and Warn about any unexpected/dangerous Words or Actions'
inputs:
  words-to-scan-for:
    description: 'Words to Search for in the PR'
    required: true
outputs:
  annotations:
    description: 'The Annotations to display'
runs:
  using: 'node16'
  main: 'index.js'
