name: 'PR Scan and Warn'
description: 'Scan the Changes in a PR and Warn about any unexpected/dangerous Words or Actions'
inputs:
  token:
    description: 'GitHub Token to access the Repo'
    required: true
  words-to-scan-for:
    description: 'Words to Search for in the PR'
    required: true
  action-type:
    description: 'The WorkFlow Event that invoked this Action'
    default: 'master'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
